/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author juand
 */
public class VistaRequerimientosReto5GUI extends javax.swing.JFrame {

    /**
     * Creates new form VistaRequerimientosReto5GUI
     */
    public VistaRequerimientosReto5GUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brnRequerimiento3 = new javax.swing.JButton();
        brnRequerimiento1 = new javax.swing.JButton();
        brnRequerimiento2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brnRequerimiento3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brnRequerimiento3.setText("Requerimiento 3");
        brnRequerimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRequerimiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(brnRequerimiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 22, -1, 100));

        brnRequerimiento1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brnRequerimiento1.setText("Requerimiento 1");
        brnRequerimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRequerimiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(brnRequerimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, 100));

        brnRequerimiento2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brnRequerimiento2.setText("Requerimiento 2");
        brnRequerimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRequerimiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(brnRequerimiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 22, -1, 100));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnRequerimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRequerimiento3ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento1Retos5GUI3 vr = new VistaRequerimiento1Retos5GUI3();
        vr.setVisible(true);
    }//GEN-LAST:event_brnRequerimiento3ActionPerformed

    private void brnRequerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRequerimiento1ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento1Retos5GUI vr = new VistaRequerimiento1Retos5GUI();
        vr.setVisible(true);
    }//GEN-LAST:event_brnRequerimiento1ActionPerformed

    private void brnRequerimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRequerimiento2ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento1Retos5GUI2 vr = new VistaRequerimiento1Retos5GUI2();
        vr.setVisible(true);
    }//GEN-LAST:event_brnRequerimiento2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientosReto5GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRequerimiento1;
    private javax.swing.JButton brnRequerimiento2;
    private javax.swing.JButton brnRequerimiento3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
